items=minecraft:bow
texture.bow_standby=runic_bow
texture.bow_pulling_0=runic_bow_pulling_0
texture.bow_pulling_1=runic_bow_pulling_1
texture.bow_pulling_2=runic_bow_pulling_2
nbt.display.Name=ipattern:*Rune*