type=armor
items=netherite_helmet netherite_chestplate netherite_leggings netherite_boots
texture.netherite_layer_1=./scilayer_1
texture.netherite_layer_2=./scilayer_2


nbt.display.Name=ipattern:*Defender*
